# Generated by Django 5.1.2 on 2025-12-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='social_link',
            field=models.URLField(null=True),
        ),
    ]
