# Generated by Django 5.1.2 on 2025-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_studentuser_experience_studentuser_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
